#!/usr/bin/env python3
"""
animation_generator.py
Emit Swift extension with tuned spring animations for Liquid Glass interactions.
Also prints a table to stdout for quick reference.

Usage:
  python animation_generator.py --out design-tokens/Animations.swift
"""
import argparse, sys, json
from textwrap import dedent

# Animation presets encode response, damping and blend duration values for common Liquid Glass interactions.
PRESETS = {
  "glass.snap": {"response":0.22, "damping":0.88, "blend":0.5},
  "glass.slide": {"response":0.30, "damping":0.82, "blend":0.5},
  "sheet.detent": {"response":0.38, "damping":0.80, "blend":0.65},
  "tab.bump": {"response":0.20, "damping":0.75, "blend":0.3},
  "press.scale": {"response":0.18, "damping":0.76, "blend":0.25},
  # Morphing expand animation used when glass surfaces morph into a larger shape.
  "glass.morph.expand": {"response":0.44, "damping":0.84, "blend":0.60},
  # Morphing collapse animation used when glass surfaces collapse back to a smaller shape.
  "glass.morph.collapse": {"response":0.40, "damping":0.82, "blend":0.55}
}

SWIFT = """\
// Generated by animation_generator.py
import SwiftUI

public enum LGAnimate {{
    public static let snap = .spring(response: {snapR}, dampingFraction: {snapD}, blendDuration: {snapB})
    public static let slide = .spring(response: {slideR}, dampingFraction: {slideD}, blendDuration: {slideB})
    public static let sheetDetent = .spring(response: {detR}, dampingFraction: {detD}, blendDuration: {detB})
    public static let tabBump = .spring(response: {tabR}, dampingFraction: {tabD}, blendDuration: {tabB})
    public static let pressScale = .spring(response: {prsR}, dampingFraction: {prsD}, blendDuration: {prsB})
    public static let morphExpand = .spring(response: {morphER}, dampingFraction: {morphED}, blendDuration: {morphEB})
    public static let morphCollapse = .spring(response: {morphCR}, dampingFraction: {morphCD}, blendDuration: {morphCB})
}}
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    s = SWIFT.format(
        snapR=PRESETS["glass.snap"]["response"], snapD=PRESETS["glass.snap"]["damping"], snapB=PRESETS["glass.snap"]["blend"],
        slideR=PRESETS["glass.slide"]["response"], slideD=PRESETS["glass.slide"]["damping"], slideB=PRESETS["glass.slide"]["blend"],
        detR=PRESETS["sheet.detent"]["response"], detD=PRESETS["sheet.detent"]["damping"], detB=PRESETS["sheet.detent"]["blend"],
        tabR=PRESETS["tab.bump"]["response"], tabD=PRESETS["tab.bump"]["damping"], tabB=PRESETS["tab.bump"]["blend"],
        prsR=PRESETS["press.scale"]["response"], prsD=PRESETS["press.scale"]["damping"], prsB=PRESETS["press.scale"]["blend"],
        morphER=PRESETS["glass.morph.expand"]["response"], morphED=PRESETS["glass.morph.expand"]["damping"], morphEB=PRESETS["glass.morph.expand"]["blend"],
        morphCR=PRESETS["glass.morph.collapse"]["response"], morphCD=PRESETS["glass.morph.collapse"]["damping"], morphCB=PRESETS["glass.morph.collapse"]["blend"]
    )
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(s)

    print("Preset  | response | damping | blend")
    for key, v in PRESETS.items():
        print(f"{key:12} {v['response']:8.2f} {v['damping']:8.2f} {v['blend']:6.2f}")
    print(f"Wrote {args.out}")

if __name__ == "__main__":
    sys.exit(main())
