#!/usr/bin/env python3
"""
color_system_generator.py
Generate a semantic color system for Liquid Glass components.
Emits JSON tokens and Swift code that maps tokens to Color assets or dynamic Color values.

Usage:
  python color_system_generator.py --brand "Acme" --out-json design-tokens/colors.json --out-swift design-tokens/Colors.swift
"""
import argparse, json, sys
from textwrap import dedent

DEFAULT_TOKENS = {
  "bg": {
    "base": {"light":"#0B0B0B", "dark":"#0B0B0B"},
    "elevated": {"light":"#121212", "dark":"#101010"},
    "scrim": {"light":"#00000066", "dark":"#00000099"}
  },
  "fg": {
    "primary": {"light":"#FFFFFF", "dark":"#FFFFFF"},
    "secondary": {"light":"#FFFFFFCC", "dark":"#FFFFFFCC"},
    "tertiary": {"light":"#FFFFFF99", "dark":"#FFFFFF99"}
  },
  "accent": {
    "primary": {"light":"#0A84FF", "dark":"#0A84FF"},
    "secondary": {"light":"#64D2FF", "dark":"#64D2FF"}
  },
  "state": {
    "success":{"light":"#34C759","dark":"#34C759"},
    "warning":{"light":"#FFD60A","dark":"#FFD60A"},
    "error":{"light":"#FF453A","dark":"#FF453A"}
  },
  "glass": {
    "tint": {
      "clear":{"light":"#00000000","dark":"#00000000"},
      "light":{"light":"#00000014","dark":"#FFFFFF1A"},
      "dark":{"light":"#00000033","dark":"#00000066"}
    }
  }
}

SWIFT_TEMPLATE = """\
// Generated by color_system_generator.py
import SwiftUI

public enum LGColor: String {{
    case bgBase = "bg.base"
    case bgElevated = "bg.elevated"
    case bgScrim = "bg.scrim"
    case fgPrimary = "fg.primary"
    case fgSecondary = "fg.secondary"
    case fgTertiary = "fg.tertiary"
    case accentPrimary = "accent.primary"
    case accentSecondary = "accent.secondary"
    case stateSuccess = "state.success"
    case stateWarning = "state.warning"
    case stateError = "state.error"
    case glassTintClear = "glass.tint.clear"
    case glassTintLight = "glass.tint.light"
    case glassTintDark = "glass.tint.dark"
}}

public extension Color {{
    static func lg(_ token: LGColor, scheme: ColorScheme) -> Color {{
        switch (token, scheme) {{
{cases}
        }}
    }}
}}

// Convenience styles that preserve vibrancy
public extension ShapeStyle where Self == Color {{
    static var lgPrimary: Color {{ Color.lg(.fgPrimary, scheme: .light) }}
    static var lgSecondary: Color {{ Color.lg(.fgSecondary, scheme: .light) }}
}}
"""

def hex_to_rgb(hexstr):
    hexstr = hexstr.replace("#","")
    if len(hexstr) in (8, 6):
        if len(hexstr) == 8:
            hexstr = hexstr[2:]  # ignore alpha in RGB conversion
    r = int(hexstr[0:2], 16)
    g = int(hexstr[2:4], 16)
    b = int(hexstr[4:6], 16)
    return f"{r/255.0:.4f}, {g/255.0:.4f}, {b/255.0:.4f}"

def make_cases(tokens):
    cases = []
    def emit(key, paths, node):
        if isinstance(node, dict) and "light" in node and "dark" in node:
            swift_token = paths.replace(".", "").replace("-", "").title()
            # Map to sRGB Color for light/dark
            lrgb = hex_to_rgb(node["light"])
            drgb = hex_to_rgb(node["dark"])
            cases.append(f'        case (.{paths.replace(".","").replace("/","")}, .light): return Color(red: {lrgb})')
            cases.append(f'        case (.{paths.replace(".","").replace("/","")}, .dark): return Color(red: {drgb})')
        else:
            for k,v in node.items():
                emit(k, f"{paths}.{k}" if paths else k, v)
    # Build enum name mapping used in switch
    enum_map = {
        "bg.base":"bgBase",
        "bg.elevated":"bgElevated",
        "bg.scrim":"bgScrim",
        "fg.primary":"fgPrimary",
        "fg.secondary":"fgSecondary",
        "fg.tertiary":"fgTertiary",
        "accent.primary":"accentPrimary",
        "accent.secondary":"accentSecondary",
        "state.success":"stateSuccess",
        "state.warning":"stateWarning",
        "state.error":"stateError",
        "glass.tint.clear":"glassTintClear",
        "glass.tint.light":"glassTintLight",
        "glass.tint.dark":"glassTintDark",
    }
    # Iterate leaves
    for path, enumname in enum_map.items():
        # Navigate to node
        parts = path.split(".")
        node = tokens
        for p in parts:
            node = node[p]
        lrgb = hex_to_rgb(node["light"])
        drgb = hex_to_rgb(node["dark"])
        cases.append(f"        case (.{enumname}, .light): return Color(red: {lrgb})")
        cases.append(f"        case (.{enumname}, .dark): return Color(red: {drgb})")
    return "\n".join(cases)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--brand", default="Default")
    parser.add_argument("--out-json", required=True)
    parser.add_argument("--out-swift", required=True)
    args = parser.parse_args()

    with open(args.out_json, "w", encoding="utf-8") as f:
        json.dump(DEFAULT_TOKENS, f, indent=2)

    cases = make_cases(DEFAULT_TOKENS)
    swift = SWIFT_TEMPLATE.replace("{cases}", cases)
    with open(args.out_swift, "w", encoding="utf-8") as f:
        f.write(swift)

    print(f"Wrote {args.out_json} and {args.out_swift}")

if __name__ == "__main__":
    sys.exit(main())
