#!/usr/bin/env python3
import json, argparse

TEMPLATE = """
// Generated by diff_migration_plan_swiftdata.py
import SwiftData

enum SchemaV1: VersionedSchema {
    static var versionIdentifier: String { "V1" }
    static var models: [any PersistentModel.Type] { [%SCHEMA_V1_MODELS%] }
    %SCHEMA_V1_MODELS_DECL%
}

enum SchemaV2: VersionedSchema {
    static var versionIdentifier: String { "V2" }
    static var models: [any PersistentModel.Type] { [%SCHEMA_V2_MODELS%] }
    %SCHEMA_V2_MODELS_DECL%
}

enum AppMigrationPlan: SchemaMigrationPlan {
    static var schemas: [any VersionedSchema.Type] { [SchemaV1.self, SchemaV2.self] }
    static var stages: [MigrationStage] {
        [
            .lightweight(fromVersion: SchemaV1.self, toVersion: SchemaV2.self)
        ]
    }
}
"""

def to_model_decl(models):
    decls = []
    decl_names = []
    for m in models:
        name = m["name"]
        decl_names.append(f"{name}.self")
        decls.append(f"@Model\nfinal class {name} {{ var _id: UUID; init(_id: UUID = UUID()) {{ self._id = _id }} }}")
    return ", ".join(decl_names), "\n".join(decls)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--old", required=True)
    ap.add_argument("--new", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    with open(args.old) as f: old = json.load(f)
    with open(args.new) as f: new = json.load(f)

    v1_models = old.get("models", [])
    v2_models = new.get("models", [])

    v1_names, v1_decl = to_model_decl(v1_models)
    v2_names, v2_decl = to_model_decl(v2_models)

    content = TEMPLATE.replace("%SCHEMA_V1_MODELS%", v1_names)\
                      .replace("%SCHEMA_V2_MODELS%", v2_names)\
                      .replace("%SCHEMA_V1_MODELS_DECL%", v1_decl)\
                      .replace("%SCHEMA_V2_MODELS_DECL%", v2_decl)

    with open(args.out, "w") as f:
        f.write(content)
    print(f"Wrote migration plan skeleton to {args.out}")

if __name__ == "__main__":
    main()
