#!/usr/bin/env python3
import json, argparse

PRIMITIVES = {"String":"String","Int":"Int","Double":"Double","UUID":"UUID","Date":"Date","Bool":"Bool","Data":"Data"}

HEADER = """
// Generated by generate_swiftdata_models.py
// Input schema -> SwiftData @Model classes
import Foundation
import SwiftData
"""

def swift_default(attr):
    if "default" not in attr: return None
    dv = attr["default"]
    if dv == "now" and attr["type"] == "Date":
        return "Date()"
    if isinstance(dv, bool):
        return "true" if dv else "false"
    if isinstance(dv, (int, float)):
        return str(dv)
    if isinstance(dv, str) and attr["type"] == "String":
        return f'\"{dv}\"'
    return None

def emit_model(m):
    name = m["name"]
    attrs = m.get("attributes", [])
    rels = m.get("relationships", [])
    lines = []
    lines.append(f"@Model\nfinal class {name} {{")
    for a in attrs:
        t = a["type"]
        optional = a.get("optional", False)
        unique = a.get("unique", False)
        swift_type = PRIMITIVES.get(t, t)
        if optional:
            swift_type += "?"
        attr_line = "    "
        if unique:
            attr_line += "@Attribute(.unique) "
        attr_line += f"var {a['name']}: {swift_type}"
        lines.append(attr_line)
    for r in rels:
        dest = r["destination"]
        to_many = r.get("toMany", False)
        dr = r.get("deleteRule", "nullify")
        inverse = r.get("inverse", None)
        inverse_str = f", inverse: \\{dest}.{inverse}" if inverse else ""
        if to_many:
            prop = f"var {r['name']}: [{dest}]"
        else:
            prop = f"var {r['name']}: {dest}?"
        lines.append(f"    @Relationship(deleteRule: .{dr}{inverse_str}) {prop}")
    inits = []
    assigns = []
    for a in attrs:
        pname = a["name"]
        t = PRIMITIVES.get(a["type"], a["type"])
        if a.get("optional", False):
            t += "?"
        dflt = swift_default(a)
        if dflt is None and a.get("unique") and a["type"] == "UUID":
            dflt = "UUID()"
        init_param = f"{pname}: {t}"
        if dflt is not None:
            init_param += f" = {dflt}"
        inits.append(init_param)
        assigns.append(f"self.{pname} = {pname}")
    for r in rels:
        pname = r["name"]
        if r.get("toMany", False):
            inits.append(f"{pname}: [{r['destination']}] = []")
        else:
            inits.append(f"{pname}: {r['destination']}? = nil")
        assigns.append(f"self.{pname} = {pname}")
    lines.append(f"    init({', '.join(inits)}) {{")
    for s in assigns:
        lines.append(f"        {s}")
    lines.append("    }")
    lines.append("}\n")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    with open(args.schema) as f:
        schema = json.load(f)
    models = schema.get("models", [])
    out = [HEADER]
    for m in models:
        out.append(emit_model(m))
    with open(args.out, "w") as f:
        f.write("\n".join(out))
    print(f"Wrote SwiftData models to {args.out}")

if __name__ == "__main__":
    main()
