#!/usr/bin/env python3
import json, argparse

HEADER = """
// Generated by generate_coredata_model_code.py
// Input schema -> NSManagedObject subclasses + in-code NSManagedObjectModel
import Foundation
import CoreData
"""

TYPE_MAP = {
    "String": ".stringAttributeType",
    "Int": ".integer64AttributeType",
    "Double": ".doubleAttributeType",
    "UUID": ".UUIDAttributeType",
    "Date": ".dateAttributeType",
    "Bool": ".booleanAttributeType",
    "Data": ".binaryDataAttributeType"
}

def emit_managedclass(m):
    name = m["name"]
    attrs = m.get("attributes", [])
    rels = m.get("relationships", [])
    lines = []
    lines.append(f"@objc({name})\npublic class {name}: NSManagedObject {{}}")
    lines.append(f"extension {name} {{")
    for a in attrs:
        swift_type = {
            "String":"String","Int":"Int64","Double":"Double","UUID":"UUID","Date":"Date","Bool":"Bool","Data":"Data"
        }[a["type"]]
        optional = a.get("optional", False)
        if optional: swift_type += "?"
        lines.append(f"    @NSManaged public var {a['name']}: {swift_type}")
    for r in rels:
        if r.get("toMany", False):
            lines.append(f"    @NSManaged public var {r['name']}: NSSet?")
        else:
            lines.append(f"    @NSManaged public var {r['name']}: {r['destination']}?")
    lines.append("}\n")
    return "\n".join(lines)

def emit_model_builder(schema):
    models = schema.get("models", [])
    lines = []
    lines.append("public func makeManagedObjectModel() -> NSManagedObjectModel {")
    lines.append("    let model = NSManagedObjectModel()")
    for m in models:
        ename = m["name"]
        lines.append(f"    let {ename}_entity = NSEntityDescription()")
        lines.append(f"    {ename}_entity.name = \"{ename}\"")
        lines.append(f"    {ename}_entity.managedObjectClassName = \"{ename}\"")
    for m in models:
        ename = m["name"]
        lines.append(f"    var {ename}_props: [NSPropertyDescription] = []")
        for a in m.get("attributes", []):
            lines.append("    do {")
            lines.append("        let attr = NSAttributeDescription()")
            lines.append(f"        attr.name = \"{a['name']}\"")
            lines.append(f"        attr.attributeType = {TYPE_MAP[a['type']]}")
            opt = "true" if a.get("optional", False) else "false"
            lines.append(f"        attr.isOptional = {opt}")
            lines.append(f"        {ename}_props.append(attr)")
            lines.append("    }")
    for m in models:
        ename = m["name"]
        for r in m.get("relationships", []):
            rname = r["name"]
            dest = r["destination"]
            to_many = r.get("toMany", False)
            max_count = "0" if to_many else "1"
            min_count = "0"
            delete_rule = {
                "nullify": ".nullifyDeleteRule",
                "cascade": ".cascadeDeleteRule",
                "deny": ".denyDeleteRule"
            }.get(r.get("deleteRule","nullify"), ".nullifyDeleteRule")
            lines.append("    do {")
            lines.append("        let rel = NSRelationshipDescription()")
            lines.append(f"        rel.name = \"{rname}\"")
            lines.append(f"        rel.destinationEntity = {dest}_entity")
            lines.append(f"        rel.maxCount = {max_count}")
            lines.append(f"        rel.minCount = {min_count}")
            lines.append(f"        rel.deleteRule = {delete_rule}")
            lines.append(f"        {ename}_props.append(rel)")
            lines.append("    }")
        lines.append(f"    {ename}_entity.properties = {ename}_props")
    for m in models:
        ename = m["name"]
        uniq = [a["name"] for a in m.get("attributes", []) if a.get("unique", False)]
        if uniq:
            arrays = ", ".join([f'[\"{n}\"]' for n in uniq])
            lines.append(f"    {ename}_entity.uniquenessConstraints = [{arrays}]")
    lines.append("    model.entities = [")
    lines.extend([f"        {m['name']}_entity," for m in models])
    lines.append("    ]")
    for m in models:
        ename = m["name"]
        for r in m.get("relationships", []):
            inv = r.get("inverse")
            if inv:
                lines.append(f"    if let lhs = {ename}_entity.propertiesByName[\"{r['name']}\"] as? NSRelationshipDescription,")
                lines.append(f"       let rhs = {r['destination']}_entity.propertiesByName[\"{inv}\"] as? NSRelationshipDescription {{")
                lines.append("        lhs.inverseRelationship = rhs")
                lines.append("    }")
    lines.append("    return model")
    lines.append("}\n")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--schema", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    with open(args.schema) as f:
        schema = json.load(f)
    out = [HEADER]
    for m in schema.get("models", []):
        out.append(emit_managedclass(m))
    out.append(emit_model_builder(schema))
    with open(args.out, "w") as f:
        f.write("\n".join(out))
    print(f"Wrote Core Data model code to {args.out}")

if __name__ == "__main__":
    main()
