#!/usr/bin/env python3
"""
component_generator.py

Generate SwiftUI Liquid Glass components that leverage the new iOS 26 `glassEffect` API.

This utility emits a single Swift file defining a component that wraps your content in a
rounded rectangle and applies the appropriate `glassEffect` style.  It supports three
variants: `clear`, `tinted`, and `prominent`.  Unlike earlier versions of this script
which relied on `Material` and blur overlays, this generator uses the modern `Glass`
styles introduced in iOS 26.

Example:

    python component_generator.py --name GlassCard --variant tinted --corner 20 --tint 0.12 --out components/GlassCard.swift

This will create `GlassCard.swift` containing a `GlassCard` struct that uses
`.glassEffect(.regular.tint(...))` for the tinted variant.  A preview provider is
included for interactive Xcode previews.
"""

import argparse
import sys
from textwrap import dedent

TEMPLATE = """\
// Generated by component_generator.py
// DO NOT EDIT BY HAND

import SwiftUI

public struct {name}: View {{
    /// Variants control the tint applied to the glass effect.  `clear` uses `.clear`,
    /// `tinted` applies a subtle tint to improve contrast, and `prominent` applies a heavier tint for legibility.
    public enum Variant: String {{
        case clear
        case tinted
        case prominent
    }}

    public var variant: Variant
    public var cornerRadius: CGFloat
    public var tintOpacity: Double
    @Environment(\.colorScheme) private var scheme
    @Environment(\.accessibilityContrast) private var accContrast

    public init(variant: Variant = .{variant}, cornerRadius: CGFloat = {corner}, tintOpacity: Double = {tint}) {{
        self.variant = variant
        self.cornerRadius = cornerRadius
        self.tintOpacity = tintOpacity
    }}

    public var body: some View {{
        VStack(alignment: .leading, spacing: 8) {{
            Text("{name}")
                .font(.title3.weight(.semibold))
                .foregroundStyle(.primary)
            Text("A production‑ready Liquid Glass surface using iOS 26 glassEffect APIs.")
                .font(.footnote)
                .foregroundStyle(.secondary)
        }}
        .padding(16)
        .glassEffect(glassStyle, in: .rect(cornerRadius: cornerRadius))
        .shadow(color: .black.opacity(0.2), radius: 16, x: 0, y: 8)
        .accessibilityElement(children: .combine)
    }}

    /// Computes the appropriate glass style based on the variant and environment.
    private var glassStyle: Glass {{
        switch variant {{
        case .clear:
            return .clear
        case .tinted:
            let base = (scheme == .dark ? Color.white : Color.black).opacity(tintOpacity)
            return .regular.tint(base)
        case .prominent:
            let base = Color.black.opacity(max(0.18, tintOpacity))
            return .regular.tint(base)
        }}
    }}
}}

#Preview("{name}") {{
    {name}(variant: .{variant}, cornerRadius: {corner}, tintOpacity: {tint})
        .padding()
        .background(Image("GlassDemoBG").resizable().scaledToFill().ignoresSafeArea())
}}
"""

def main() -> int:
    parser = argparse.ArgumentParser(description="Generate SwiftUI Liquid Glass components.")
    parser.add_argument("--name", required=True, help="Component struct name, e.g., GlassCard")
    parser.add_argument("--variant", default="clear", choices=["clear", "tinted", "prominent"],
                        help="Initial variant of the glass surface")
    parser.add_argument("--corner", type=int, default=20, help="Corner radius for the rounded rectangle")
    parser.add_argument("--tint", type=float, default=0.08, help="Tint opacity used for tinted/prominent variants")
    parser.add_argument("--out", required=True, help="Output Swift file path")
    args = parser.parse_args()

    # Render the Swift template with provided parameters.
    src = TEMPLATE.format(name=args.name, variant=args.variant, corner=args.corner, tint=args.tint)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(src)
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())