#!/usr/bin/env python3
"""
delegate_bridge_generator.py
Generate delegate bridging patterns: map delegate callbacks into SwiftUI via closures or bindings.
Produces a Swift file showing a representable + coordinator with selected delegate methods.
"""
import argparse
from pathlib import Path
from typing import List

TEMPLATES = {
    "UITableView": {
        "imports": "import SwiftUI\nimport UIKit",
        "protocols": ["UITableViewDelegate", "UITableViewDataSource"],
        "callbacks": [
            ("didSelectRowAt", "func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) { parent.onSelect?(indexPath.row) }"),
            ("commitEditingStyle", "func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) { parent.onCommitDelete?(indexPath) }"),
        ],
    },
    "MKMapView": {
        "imports": "import SwiftUI\nimport MapKit",
        "protocols": ["MKMapViewDelegate"],
        "callbacks": [
            ("regionDidChangeAnimated", "func mapView(_ mapView: MKMapView, regionDidChangeAnimated animated: Bool) { parent.region = mapView.region }"),
        ],
    },
    "WKWebView": {
        "imports": "import SwiftUI\nimport WebKit",
        "protocols": ["WKNavigationDelegate"],
        "callbacks": [
            ("didFinish", "func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) { parent.isLoading = false }"),
        ],
    },
}

HEADER = """// Generated by delegate_bridge_generator.py
// This file maps delegate callbacks to SwiftUI via bindings/closures.
"""

def build(name: str, control: str) -> str:
    if control not in TEMPLATES:
        raise SystemExit(f"Unknown control '{control}'. Supported: {', '.join(TEMPLATES)}")
    cfg = TEMPLATES[control]
    imports = cfg["imports"]
    protocols = ", ".join(cfg["protocols"])
    callback_stubs = "\n        ".join([c for _, c in cfg["callbacks"]])
    file = f"""{HEADER}
{imports}

struct {name}: UIViewRepresentable {{
    typealias UIViewType = {control}
    var onSelect: ((Int) -> Void)? = nil
    var onCommitDelete: ((IndexPath) -> Void)? = nil
    @Binding var region: MKCoordinateRegion
    @Binding var isLoading: Bool

    func makeUIView(context: Context) -> {control} {{
        let v = {control}()
        v.delegate = context.coordinator
        return v
    }}

    func updateUIView(_ uiView: {control}, context: Context) {{
        // Keep delegate up-to-date
        // Additional sync goes here
    }}

    static func dismantleUIView(_ uiView: {control}, coordinator: Coordinator) {{
        uiView.delegate = nil
    }}

    final class Coordinator: NSObject, {protocols} {{
        weak var parentRef: {name}?
        init(_ parent: {name}) {{ self.parentRef = parent }}

        {callback_stubs}
    }}

    func makeCoordinator() -> Coordinator {{ Coordinator(self) }}
}}
"""
    return file

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="DelegatedBridge")
    ap.add_argument("--control", choices=list(TEMPLATES.keys()), default="UITableView")
    ap.add_argument("--output", default="./out")
    args = ap.parse_args()

    content = build(args.name, args.control)
    Path(args.output).mkdir(parents=True, exist_ok=True)
    path = Path(args.output) / f"{args.name}.swift"
    path.write_text(content, encoding="utf-8")
    print(f"[delegate_bridge_generator] Wrote {path}")

if __name__ == "__main__":
    main()
