#!/usr/bin/env python3
"""
coordinator_generator.py
Generate a Coordinator implementation skeleton for a given control/delegate.
Supports common UIKit/AppKit controls; accepts custom protocols as comma-separated list.
"""
import argparse
from pathlib import Path
from typing import List

DEFAULT_PROTOCOLS = {
    "UITableView": ["UITableViewDelegate", "UITableViewDataSource"],
    "MKMapView": ["MKMapViewDelegate"],
    "WKWebView": ["WKNavigationDelegate", "WKUIDelegate"],
    "NSTableView": ["NSTableViewDelegate", "NSTableViewDataSource"],
}

HEADER = """// Generated by coordinator_generator.py
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif
"""

def generate(name: str, control: str, protocols: List[str]) -> str:
    protos = ", ".join(protocols) if protocols else ""
    body = f"""
final class {name}: NSObject{ (', ' + protos) if protos else '' } {{
    weak var owner: AnyObject?
    init(owner: AnyObject?) {{
        self.owner = owner
        super.init()
    }}
    // MARK: - Update with latest SwiftUI state
    func sync(_ info: [String: Any]) {{
        // Apply derived state from SwiftUI here.
    }}
    // MARK: - Delegate/DataSource hooks (add what you need)
    // Example for table view (uncomment where relevant):
    /*
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {{ return 0 }}
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {{
        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") ?? UITableViewCell(style: .default, reuseIdentifier: "Cell")
        cell.textLabel?.text = "Row \\(indexPath.row)"
        return cell
    }}
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {{
        // Forward selection to SwiftUI via a closure or binding.
    }}
    */
}}
"""
    return HEADER + body

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=False, default="Coordinator")
    ap.add_argument("--control", required=False, default="UITableView")
    ap.add_argument("--protocols", help="Comma-separated protocol names (override defaults)")
    ap.add_argument("--output", default="./out")
    args = ap.parse_args()

    protos = DEFAULT_PROTOCOLS.get(args.control, [])
    if args.protocols:
        protos = [p.strip() for p in args.protocols.split(",") if p.strip()]

    content = generate(args.name, args.control, protos)
    Path(args.output).mkdir(parents=True, exist_ok=True)
    path = Path(args.output) / f"{args.name}.swift"
    path.write_text(content, encoding="utf-8")
    print(f"[coordinator_generator] Wrote {path}")

if __name__ == "__main__":
    main()
